"""add html body to email queue

Revision ID: 116db0d01e5d
Revises: b40cc15d83ef
Create Date: 2026-08-11 19:33:49.634082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116db0d01e5d'
down_revision: Union[str, Sequence[str], None] = 'b40cc15d83ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
    "email_queue",
    sa.Column(
        "html_body",
        sa.Text(),
        nullable=True,
    ),
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
