"""create reading history table

Revision ID: b0b04902c4ef
Revises: d61e2dc0d60d
Create Date: 2026-08-06 15:37:48.046315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b04902c4ef'
down_revision: Union[str, Sequence[str], None] = 'd61e2dc0d60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "reading_history",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "article_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "viewed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "article_id",
            name="uq_reading_history_user_article",
        ),
    )

    op.create_index(
        op.f("ix_reading_history_id"),
        "reading_history",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_reading_history_user_id"
        ),
        "reading_history",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_reading_history_article_id"
        ),
        "reading_history",
        ["article_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
