"""create bookmarks table

Revision ID: d61e2dc0d60d
Revises: fe375046b205
Create Date: 2026-08-05 22:27:57.313673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61e2dc0d60d'
down_revision: Union[str, Sequence[str], None] = 'fe375046b205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "bookmarks",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "article_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "article_id",
            name="uq_bookmarks_user_article",
        ),
    )

    op.create_index(
        op.f("ix_bookmarks_id"),
        "bookmarks",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_bookmarks_user_id"),
        "bookmarks",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_bookmarks_article_id"),
        "bookmarks",
        ["article_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
